language: node_js
node_js:
- 8
script:
- yarn run lint
- yarn test
after_success: yarn run coverage
deploy:
  provider: npm
  email: rplan-ci@actano.de
  api_key:
    secure: o4ajsIK5Wb9aNLwLpt8+zgBCtDJfD1PFocqsooLo3Yt4vvUaI3WLsLuvqkpO10CvkijOhdrErTk7/ujPyIsGAwUSA0TR3DKiMWgBOfUraaVy2wLQCuHMpowOhQ6LBHzfGgNRBxg/jCUNL8eWiqUlOaC/jNgamgcQVBP2BhMRdTBqXoujxgWdIwfqtn53r+VO5Bs0HW29MCf1Umwz8dFxHs+QA15Ly37Y6RryVmZOjIOqqQQek0oCfCGIyirV1SKo3q6R7OMhsFfwW0fTV4caSk42XsZ0fGYAUP2QNCrqVx3JNuz9cz24MZh2jljzFgxLGT6OWaAjYDyTkVuZArI8FZKOaLz/r5J9mNV8y++xoZmqwpdyFCNEVVOPILYab/r5VVusu59EK3YUyu6SbyiYWLbo1owLUo2tajgKZBFsnmEHQlbGcMaEqLhsvDiYR2dxJz4RuXDU91CMot77WWlGyccDFcJ05v+fzfhTn1o5iRs1LlIq+TCKYvwNYWeH9cnIB7Amrg5sXPF9aoj3LUuVicBan7m3yCu7VvS0aN2R4xvikQQtbANGNHvBXps3nL21XELTFTp8FrdlMbQ/Ww20UPzx9v7PDKtn7Vl664dQ5lsZRU/8Il3fCQL/PB1UdFvMHTTKXGTSMfTD3u6UYaN/NbwIXfxQUqxIGI01A6O8jts=
  on:
    tags: true
    repo: actano/yourchoice-redux
