language: node_js
node_js:
- 6.0.0
script:
- yarn run lint
- yarn test
after_success: yarn run coverage
deploy:
  provider: npm
  email: marcus.mennemeier@actano.de
  api_key:
    secure: UP8onNoQ8Hw+N8Of/JvraxRjxppTTYyHktM7thd5BwAWb0DG6VR7RsPubuKdDpEYVLViWUsITRaFvKJAHdzVN5aW2ggqB48b+798NOPlWcdbEHFTheHgpwASkjJxIHGFzfQQa178AjrmZcZP0ek6ze9wAgpznwW4JtaABYbScaigrJraEQ/mELFPiFwKG1BY3xoU5fWLtBUYCsQDmbeXyMa5Tm4D5kvcpQMh9AcBmCvH7U0Hzm/lWKV+dCxPfirrsdz4aHP4lSIay1/4cjQw7uhdaZUkif/lHFmeO21J2pYMx3sgGzn6EuPNGJCnFsjnHXhyA82BFOj4dRxbv2RITza6H/qxqWa+dgXJdl2FONcbkxbar8DOjoS/TK/HHOYVK62z+vrtxM8LpNlWo7aQk1xUhMpmck6z+BM+UCfcZ5AEJh5/T9tS3ah9Mfj2IPqOG79g0Lz3+waCKLLvRDwln1sETCbnQi2J5rcwBXLK14090vtwtYZJloUybmqYWW7twSR+/+vTroIuXbKFEEErcctwFstjHfUl0gWPDqzkPGPoLjtsCQcabN6u3nUxgXgB3/Th45tNOKWHWlNizmwmivtRETLF64c4i4733FAhaUvhf4gSHbMbgJsTDfjAiZonW8NLuAxe2x9Vc3h3laldFxNkvYaZqsM3rMRss7H7yU0=
  on:
    tags: true
    repo: actano/yourchoice-redux
